version: '3'

services:
  app:
    image: image-service
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/imageservice
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}